language: node_js
node_js:
  - 'iojs'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install wget
  - wget --no-check-certificate https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - sudo dpkg -i hugo_0.15_amd64.deb
  - npm install --global shipit-cli@1.4.1
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_2d73131b242d_key -iv $encrypted_2d73131b242d_iv -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
  - sudo chmod 600 ~/.ssh/id_rsa
install:
  - npm install
  - mkdir themes
  - git clone git@github.com:fer2d2/thezombietheme.git themes/thezombietheme
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
