baseurl="https://www.procesozombie.com"
languageCode = "es-ES"
title = "El proceso zombie"

MetaDataFormat = "toml"
theme = "thezombietheme"

paginate = 8
PaginatePath = "/"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "Desarrollo de software, tecnología, código abierto y curiosidades"

    author = "Fernando Moro Hernández"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Desarrollo de software, tecnología, código abierto y curiosidades."
    keywords = "desarrollo, programación, software, tecnología, curiosidades, linux"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    github = "https://github.com/fer2d2"
    bitbucket = "https://bitbucket.org/Fer2d2/"
    twitter = "https://twitter.com/fer2d2"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "UA-73307155-1"

    disqus = "elprocesozombie"
[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "inicio"
    url        = ""
    weight     = 1

    [[menu.main]]
    identifier = "about"
    name       = "acerca de"
    url        = "#"
    weight     = 2
